language: c
sudo: false
services:
  - docker
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash ./.travis-docker.sh
env:
  global:
  - PACKAGE=discord-ml
  - OCAML_VERSION=4.09
deploy:
  provider: pages:git
  keep_history: false
  local_dir: _build/install/default/bin/
  token: $GITHUB_TOKEN
  edge: true # opt in to dpl v2