language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
env:
  global:
  - PACKAGE=discord-ml
  - DISTRO=debian-stable
  - OCAML_VERSION=4.09
deploy:
  provider: pages:git
  keep_history: false
  #local_dir: _build/install/default/bin/
  token: $GITHUB_TOKEN
  edge: true # opt in to dpl v2