# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        # A directory to store and save the cache
        path: ~/.opam
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-build
    - name: Set up OCaml
      uses: avsm/setup-ocaml@v1.0.1
      with:
        # Version of the OCaml compiler to initialise
        ocaml-version: 4.09.1
    - run: opam pin add discord-ml.dev . --no-action
    - run: opam depext discord-ml --yes #--with-test
    - run: opam install . --deps-only # --with-doc --with-test
    - run: opam exec -- dune build
    - run: opam exec -- dune runtest
    - run: mkdir dist && cp _build/default/bin/bot.exe dist/bot.exe
    - run: cp Procfile dist/Procfile
    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.gh_token }}
